name: gma_frontend
description: "GMA - PDF-Linked Markdown Annotation App"
publish_to: 'none'
version: 1.0.4+6

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # UI
  shadcn_ui: ^0.45.1
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # PDF Viewer
  pdfrx: ^2.2.0

  # Local Storage
  hive_flutter: ^1.1.0

  # Model
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Markdown
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+6
  flutter_math_fork: ^0.7.2

  # File System
  path_provider: ^2.1.4
  path: ^1.9.0
  file_picker: ^8.1.6

  # Drawing
  perfect_freehand: ^2.5.2+1

  # HTTP
  http: ^1.2.0

  # Utils
  uuid: ^4.5.1
  yaml: ^3.1.2
  intl: ^0.20.2
  marionette_flutter: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
